version: '3.8'

services:

  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - '3306:3306'
    volumes:
      - sql-data:/var/lib/mysql

volumes:
  sql-data:
